"""empty message

Revision ID: 8e30710abf3a
Revises: cd339affc1b1
Create Date: 2020-02-15 15:45:50.751735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e30710abf3a'
down_revision = 'cd339affc1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hoa_don', sa.Column('giam_gia', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hoa_don', 'giam_gia')
    # ### end Alembic commands ###
